#!/bin/bash
ip link set dev eth0 up # vers client 2 et serveur_web
ip addr add 192.168.84.195/26 dev eth0

ip link set dev eth1 up # vers fai
ip addr add 8.29.2.33/27 dev eth1

ip route add default via 8.29.2.34 #R_FAI

echo 1 >/proc/sys/net/ipv4/ip_forward
service isc-dhcp-server start

iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

#bloquer tout
iptables -P INPUT DROP 
iptables -P OUTPUT DROP 
iptables -P FORWARD DROP

#accepter ping
iptables -A INPUT -p icmp -j ACCEPT
iptables -A OUTPUT -p icmp -j ACCEPT
iptables -A FORWARD -p icmp -j ACCEPT

#accepter HTTP

iptables -t filter -A FORWARD -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -p tcp --sport 80 -j ACCEPT

#accepter DNS

iptables -t filter -A FORWARD -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -p udp --sport 53 -j ACCEPT

#Service web client

iptables -t nat -A PREROUTING -p tcp -d 8.29.2.33 --dport 80 -j DNAT --to 192.168.84.194
