#!/bin/bash

# vers FAI
ip link set dev eth0 up
ip addr add 8.29.2.67/27 dev eth0

# vers RSR
ip link set dev eth1 up
ip addr add 8.29.2.129/27 dev eth1

# routage statique
#ip route add 8.29.2.96/27 via 8.29.2.66 #R1
#ip route add 8.29.2.160/27 via 8.29.2.130 #RSR
#ip route add 8.29.2.192/27 via 8.29.2.130 #RSR
#ip route add 8.29.2.224/27 via 8.29.2.130 #RSR
#ip route add default via 8.29.2.65 # R_FAI

# routage dynamique
echo 1 > /proc/sys/net/ipv4/ip_forward

service quagga start
